### ISSUE TITLE
Can I use this tool for my use case?

### ISSUE THREAD

**Issue by Rayman** [trainman419/catkin_workspace#2]
Hey, I'm looking for a tool to manage my ROS workspace. I work with a robot where we have a mix of default ROS packages, custom ROS packages and forked versions of several packages. Can I use your tool to manage (create/update) this workspace?

Ideally it should work like this:

```
catkin_workspace_create robot-main-meta-package --distribution=custom-ros-config.yaml
```

It should recursively check out `robot-main-meta-package` and its dependencies while choosing the version specified in the yaml file. For example
- navigation stack should be our forked version: https://github.com/tue-robotics/navigation
- all our custom packages should be checked out from source at https://github.com/tue-robotics/*
- for the rest use the default `ros-{version}-` package

**Comment by trainman419** [comment]
I never implemented this; it's just a design idea. You may want to look at catkin_tools instead.

**Comment by Rayman** [comment]
Thanks! After some more googling I think `rosinstall_generator` with a [custom_rosdistro](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/custom_rosdistro.rst) will fit my use case.
